# Generated by Django 6.1 on 2026-09-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribtionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscribtion',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='subscribtion',
            name='title',
        ),
        migrations.AlterField(
            model_name='subscribtion',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='subscribtion',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.subscribtiontype'),
        ),
    ]
