# Generated by Django 6.1 on 2026-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_subscribtiontype_alter_subscribtion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribtiontype',
            options={'verbose_name': 'Вид подписки', 'verbose_name_plural': 'Виды подписки'},
        ),
        migrations.AlterField(
            model_name='subscribtiontype',
            name='title',
            field=models.TextField(blank=True, verbose_name='Название'),
        ),
    ]
