# Generated by Django 6.1 on 2026-09-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_category_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.category', verbose_name='Жанр фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Оценка'),
        ),
        migrations.RenameModel(
            old_name='SubscribtionType',
            new_name='SubscriptionType',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(null=True, verbose_name='Длительность')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.subscriptiontype', verbose_name='Вид подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.DeleteModel(
            name='Subscribtion',
        ),
    ]
