# Generated by Django 6.1 on 2026-09-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_category_options_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Длительность'),
        ),
    ]
