# Generated by Django 6.1 on 2026-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_subscription_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Длительность (дней)'),
        ),
    ]
