# Generated by Django 6.1 on 2026-09-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_genre_title_alter_movie_title_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Подписка пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
    ]
