# Generated by Django 6.1 on 2026-09-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_rename_genre_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
