# Generated by Django 6.1 on 2026-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_usersubscription_is_active_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='date_start',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
