# Generated by Django 6.1 on 2026-09-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Цена'),
        ),
    ]
