# Generated by Django 6.1 on 2026-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_alter_subscription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='date_start',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_payment',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего списания'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Статус подписки'),
        ),
    ]
