# Generated by Django 6.1 on 2026-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_remove_usersubscription_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='last_payment',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего списания'),
        ),
    ]
